# Generated by Django 5.2.1 on 2025-05-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBelongsTo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_modified', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('unisex', 'Unisex'), ('girl_kid', 'Girl Kid'), ('boy_kid', 'Boy Kid'), ('unisex_kid', 'Unisex Kid')], default='unisex', max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_modified', models.DateTimeField(auto_now=True)),
                ('product_class', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('order_count', models.IntegerField()),
                ('total_item', models.IntegerField()),
                ('out_of_stock', models.BooleanField(default=False)),
                ('item_belongs_to', models.ManyToManyField(related_name='belongs_to', to='home.productbelongsto')),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_class', to='home.productclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
